// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID    string  `json:"id"`
	Name  *string `json:"name,omitempty"`
	Price *string `json:"price,omitempty"`
}

type ProductInput struct {
	Name  *string `json:"name,omitempty"`
	Price *string `json:"price,omitempty"`
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
}

type UserInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
